import { useState, useEffect } from "react";
import Head from "next/head";
import meetups from "../../public/meetups.png";
import design from "../../public/merneats.png";
import quotes from "../../public/quotes.png";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Link from "next/link";


function Projects() {
    const [darkMode, setDarkMode] = useState(true);
    useEffect(() => {
        const storedDarkMode = localStorage.getItem("darkMode");
        if (storedDarkMode !== null) {
            setDarkMode(JSON.parse(storedDarkMode));
        }
    }, []);
    const toggleDarkMode = () => {
        const newDarkMode = !darkMode;
        setDarkMode(newDarkMode);
        localStorage.setItem("darkMode", JSON.stringify(newDarkMode));
    };
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-white px-10 dark:bg-gray-900">
                <nav className="py-10 mb-12 gap-8 flex flex-wrap  justify-between dark:text-white md:px-20 lg:px-40">
                    <h1 className="font-burtons text-xl text-center w-full md:w-auto"><Link href='/'>harshit'sPortfolio</Link></h1>
                    <ul className="flex flex-wrap items-center justify-center gap-4 w-full md:w-auto">
                        <li>
                            <Link href='/projects'>PROJECTS</Link>
                        </li>
                        <li>
                            <BsFillMoonStarsFill
                                onClick={toggleDarkMode}
                                className=" cursor-pointer text-2xl ml-8"
                            />
                        </li>
                        <li>
                            <a
                                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                                href="/resume/22bcs103_harshit_1.pdf" // Path to your resume PDF
                                target="_blank" // Open in a new tab
                                rel="noopener noreferrer"
                            >
                                Resume
                            </a>
                        </li>
                    </ul>
                </nav>
                <section>
                    <div className="text-center md:px-40">
                        <h3 className="text-3xl py-1 dark:text-white ">Projects Showcase</h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Explore my collection of projects highlighting my skills in programming, problem-solving, and web development. Each project reflects my dedication to learning and creating efficient software solutions.
                        </p>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Dive into my journey as a third-year B.Tech student at IIIT Jabalpur, showcasing real-world applications and innovative designs built with modern technologies.
                        </p>
                    </div>
                    <div className="lg:flex gap-10">
                        <div className="text-center shadow-lg  rounded-xl my-10  dark:bg-white flex-1">
                            <Image src={design} width={1000} height={100} className="rounded-t-xl"/>
                            <div className="p-10">
                                <h3 className="text-lg font-medium pt-8 pb-2  ">
                                    Beautiful Designs
                                </h3>
                                <p className="py-2">
                                    Creating elegant designs suited for your needs following core
                                    design theory.
                                </p>
                                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                                <p className="text-gray-800 py-1">Photoshop</p>
                                <p className="text-gray-800 py-1">Illustrator</p>
                                <p className="text-gray-800 py-1">Figma</p>
                                <p className="text-gray-800 py-1">Indesign</p>
                            </div>
                        </div>
                        <div className="text-center shadow-lg  rounded-xl my-10  dark:bg-white flex-1">
                            <Image src={meetups} width={1000} height={100} className="rounded-t-xl"/>
                            <div className="p-10">
                                <h3 className="text-lg font-medium pt-8 pb-2  ">
                                    Beautiful Designs
                                </h3>
                                <p className="py-2">
                                    Creating elegant designs suited for your needs following core
                                    design theory.
                                </p>
                                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                                <p className="text-gray-800 py-1">Photoshop</p>
                                <p className="text-gray-800 py-1">Illustrator</p>
                                <p className="text-gray-800 py-1">Figma</p>
                                <p className="text-gray-800 py-1">Indesign</p>
                            </div>
                        </div>
                        <div className="text-center shadow-lg  rounded-xl my-10  dark:bg-white flex-1">
                            <Image src={quotes} width={1400} height={100} className="rounded-t-xl"/>
                            <div className="p-10">
                                <h3 className="text-lg font-medium pt-8 pb-2  ">
                                    Beautiful Designs
                                </h3>
                                <p className="py-2">
                                    Creating elegant designs suited for your needs following core
                                    design theory.
                                </p>
                                <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
                                <p className="text-gray-800 py-1">Photoshop</p>
                                <p className="text-gray-800 py-1">Illustrator</p>
                                <p className="text-gray-800 py-1">Figma</p>
                                <p className="text-gray-800 py-1">Indesign</p>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}

export default Projects;