import { useState, useEffect } from "react";
import Head from "next/head";
import meetups from "../../public/meetups.png";
import design from "../../public/merneats.png";
import quotes from "../../public/quotes.png";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Link from "next/link";
import { AiFillCarryOut, AiFillGithub, AiOutlineExport } from "react-icons/ai";


function Projects() {
    const [darkMode, setDarkMode] = useState(true);
    useEffect(() => {
        const storedDarkMode = localStorage.getItem("darkMode");
        if (storedDarkMode !== null) {
            setDarkMode(JSON.parse(storedDarkMode));
        }
    }, []);
    const toggleDarkMode = () => {
        const newDarkMode = !darkMode;
        setDarkMode(newDarkMode);
        localStorage.setItem("darkMode", JSON.stringify(newDarkMode));
    };
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-white px-10 dark:bg-gray-900">
            <nav className="py-10 mb-12 gap-8 flex flex-wrap  justify-between dark:text-white md:px-20 lg:px-40">
            <h1 className="font-burtons text-xl text-center w-full md:w-auto"><Link href='/'>harshit'sPortfolio</Link></h1>
            <ul className="flex flex-wrap items-center justify-center gap-4 w-full md:w-auto">
            <li>
                <Link href='/projects'>EDUCATION</Link>
              </li>
              <li>
                <Link href='/projects' className="ml-8">PROJECTS</Link>
              </li>
              <li>
                <Link
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/resume/22bcs103_harshit_1.pdf" // Path to your resume PDF
                  target="_blank" // Open in a new tab
                  rel="noopener noreferrer"
                >
                  Resume
                </Link>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={toggleDarkMode}
                  className=" cursor-pointer text-2xl ml-8"
                />
              </li>
            </ul>
          </nav>
                <section>
                    <div className="text-center md:px-40">
                        <h3 className="text-3xl py-1 dark:text-white ">Projects Showcase</h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Explore my collection of projects highlighting my skills in programming, problem-solving, and web development. Each project reflects my dedication to learning and creating efficient software solutions.
                        </p>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Dive into my journey as a third-year B.Tech student at IIIT Jabalpur, showcasing real-world applications and innovative designs built with modern technologies.
                        </p>
                    </div>
                    <div className="grid-cols-1 md:grid grid-cols-3 gap-10 p-10">
                        <div className="text-center shadow-lg  rounded-xl my-10  dark:bg-white flex-1 flex flex-col">
                            {/* <div className="relative h-56 w-full text-5xl group rounded-xl md:-m-8 shadow-lg bg-[url('/merneats.png')] bg-cover bg-center">
                                <div className="absolute rounded-xl inset-0 group-hover:bg-white group-hover:bg-opacity-50 "></div>

                                <div className="flex flex-row gap-4 mt-24 ml-40 absolute opacity-0 group-hover:opacity-100">
                                <AiOutlineExport></AiOutlineExport>
                                <AiFillGithub></AiFillGithub>
                                </div>

                            </div> */}
                            <Image src={design} width={1000} height={100} className="rounded-xl -m-8 shadow-lg" />
                                <div className="flex ml-auto text-5xl text-blue-500 bg-white border-2 border-sky-500 -mr-2 rounded-xl">
                                    <a href="https://mern-food-ordering-app-frontend-r3on.onrender.com/" target="_blank"
                                rel="noopener noreferrer"><AiOutlineExport></AiOutlineExport></a>
                                </div>
                            <div className=" flex-grow">
                                <h3 className="text-lg font-medium pt-8 pb-2  ">
                                    MERN Food Ordering Project
                                </h3>
                                <h4 className="py-4 text-teal-600">Tools</h4>
                                <div className="grid grid-cols-3">
                                <p className="text-gray-800 py-1">React</p>
                                <p className="text-gray-800 py-1">React Route</p>
                                <p className="text-gray-800 py-1">TypeScript</p>
                                <p className="text-gray-800 py-1">MongoDB</p>
                                <p className="text-gray-800 py-1">Cloudinary</p>
                                <p className="text-gray-800 py-1">Auth0</p>
                                <p className="text-gray-800 py-1">Tailwind</p>
                                <p className="text-gray-800 py-1">Shadcn</p>
                                </div>
                            </div>
                            <Link
                                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2  m-2 border-none rounded-md mt-auto"
                                href="projects/foodOrdering"

                            >
                                Details
                            </Link>
                        </div>
                        <div className="text-center shadow-lg rounded-xl my-10 dark:bg-white flex-1 flex flex-col">
                            <Image src={meetups} width={1000} height={100} className="rounded-xl -m-8 shadow-lg" /> 
                             <div className="flex ml-auto text-5xl text-blue-500 bg-white border-2 border-sky-500 -mr-2 rounded-xl">
                                    <a href="http://nextjs-meetups-pi-ten.vercel.app/" target="_blank"
                                rel="noopener noreferrer"><AiOutlineExport></AiOutlineExport></a>
                                    
                                </div>
                            <div className=" flex-grow">
                                <h3 className="text-lg font-medium pt-8 pb-2">
                                    NEXT JS React Meetups
                                </h3>
                                <h4 className="py-4 text-teal-600">Tools</h4>
                                <div className="grid grid-cols-3"><p className="text-gray-800 py-1">Nextjs</p>
                                <p className="text-gray-800 py-1">React</p>
                                <p className="text-gray-800 py-1">vercel</p></div>
                                
                            </div>
                            <Link
                                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2  m-2 border-none rounded-md mt-auto"
                                href="projects/meetups"

                            >
                                Details
                            </Link>
                        </div>

                        <div className="text-center shadow-lg  rounded-xl my-10  dark:bg-white flex-1 flex flex-col">
                        <Image src={quotes} width={1400} height={100} className="rounded-xl -m-8 shadow-lg" />
                            <div className="flex ml-auto text-5xl text-blue-500 bg-white border-2 border-sky-500 -mr-2 rounded-xl">
                                    <a href="http://hosting-a608c.web.app/" target="_blank"
                                rel="noopener noreferrer"> <AiOutlineExport></AiOutlineExport></a>
                                   
                                </div>
                            <div>
                                <h3 className="text-lg font-medium pt-8 pb-2  ">
                                    React Multi-Page Quotes Application
                                </h3>
                                <h4 className="py-4 text-teal-600">Tools</h4>
                                <div className="grid grid-cols-3">
                                <p className="text-gray-800 py-1">React</p>
                                <p className="text-gray-800 py-1">React Router</p>
                                <p className="text-gray-800 py-1">Firebase</p>
                                <p className="text-gray-800 py-1">React hooks</p>
                                </div>
                                
                            </div>
                            <Link
                                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 m-2 border-none rounded-md mt-auto"
                                href="projects/quotes" // Path to your resume PDF
                            >
                                Details
                            </Link>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}

export default Projects;