import Head from "next/head";
import {

  AiFillLinkedin,

  AiFillGithub,

  AiFillCopyrightCircle,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/hg.jpg";

import Image from "next/image";

import { useEffect } from "react";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  useEffect(() => {
    const storedDarkMode = localStorage.getItem("darkMode");
    if (storedDarkMode !== null) {
      setDarkMode(JSON.parse(storedDarkMode));
    }
  }, []);
  const toggleDarkMode = () => {
    const newDarkMode = !darkMode;
    setDarkMode(newDarkMode);
    localStorage.setItem("darkMode", JSON.stringify(newDarkMode));
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 gap-8 flex flex-wrap  justify-between dark:text-white md:px-20 lg:px-40">
            <h1 className="font-burtons text-xl text-center w-full md:w-auto"><Link href='/'>harshit'sPortfolio</Link></h1>
            <ul className="flex flex-wrap items-center justify-center gap-4 w-full md:w-auto">
              <li>
                <Link href='/projects'>PROJECTS</Link>
              </li>
              <li>
                <BsFillMoonStarsFill
                  onClick={toggleDarkMode}
                  className=" cursor-pointer text-2xl ml-8"
                />
              </li>
              <li>
                <Link
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/resume/22bcs103_harshit_1.pdf" // Path to your resume PDF
                  target="_blank" // Open in a new tab
                  rel="noopener noreferrer"
                >
                  Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center grid grid-cols-1  md:grid-cols-4 gap-0">
            <div className="col-span-3">
              <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                Harshit Gangwar
              </h2>
              <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
                Programming, problem-solving, web development.
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                Ambitious third-year B.Tech student at IIIT Jabalpur, with a keen interest in software development and a passion for solving complex problems through efficient coding solutions. Strong foundation in programming and logical thinking,constantly enhancing skills to excel in roles involving software development and web technologies.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <a href="https://github.com/harshit-G51102"> <AiFillGithub></AiFillGithub></a>
                <a href="https://www.linkedin.com/in/harshit-gangwar-5ab56b252/"><AiFillLinkedin /></a>
                <a href="https://leetcode.com/u/74RFdo6xK0/"><AiFillCopyrightCircle></AiFillCopyrightCircle></a>
              </div>
            </div>
            <div className="col-span-1 mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 relative overflow-hidden mt-0 md:h-80 md:w-80 animate-glow">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>



      </main>
    </div>
  );
}
